const songs = [
    {
        name: "Bad Things",
        singer: "Machine Gun Kelly, Camila Cabello",
        path: "/music/Bad Things - Machine Gun Kelly_ Camila C.mp3",
        thumb: "https://upload.wikimedia.org/wikipedia/en/b/b8/Bad_Things_%28Official_Single_Cover%29_by_Machine_Gun_Kelly_and_Camila_Cabello.png",
        iconStatus: '<i class="fas fa-user-friends"></i>',
        duration: "3:59",
    },
    {
        name: "I do",
        singer: "991 Band",
        path: "/music/911 – I Do.mp3",
        thumb: "https://i.ytimg.com/vi/GW0TdRPhH18/maxresdefault.jpg",
        iconStatus: '<i class="fas fa-user-friends"></i>',
        duration: "3:27",
    },
    {
        name: "Nothing Gonna Change My Love For You",
        singer: "Westlife",
        path: "/music/Westlife – Nothing's Gonna Change My Love For You.mp3",
        thumb: "https://theharmonica.vn/wp-content/uploads/2019/02/14571416029029_large.jpg",
        iconStatus: '<span class="badge">ZMA</span>',
        duration: "3:49",
    },
    {
        name: "Girls Like You",
        singer: "Maroon 5, Cardi B",
        path: "/music/Girls Like You - Maroon 5_ Cardi B.mp3",
        thumb: "https://file.tinnhac.com/resize/600x-/music/2018/12/24/20181224230252-a7ab.jpg",
        iconStatus: '<i class="fas fa-user-friends"></i>',
        duration: "3:55",
    },
    {
        name: "You Belong With Me",
        singer: "Taylor Swift",
        path: "/music/Taylor Swift – You belong with me.mp3",
        thumb: "https://avatar-ex-swe.nixcdn.com/song/2019/11/28/1/e/6/0/1574924858799_640.jpg",
        iconStatus: "",
        duration: "3:51",
    },
    {
        name: "My Love",
        singer: "Westlife",
        path: "/music/Westlife – My Love.mp3",
        thumb: "https://avatar-ex-swe.nixcdn.com/playlist/2019/01/15/b/c/6/b/1547551522561_500.jpg",
        iconStatus: "",
        duration: "3:53",
    },
    {
        name: "Beautiful In White",
        singer: "Shane Filan (Westlife)",
        path: "/music/Shane Filan – Beautiful In White.mp3",
        thumb: "/images/audio_default.png",
        iconStatus: '<i class="fas fa-user-friends"></i>',
        duration: "3:52",
    },
    {
        name: "Senorita",
        singer: "Shawn Mendes, Camila Cabello",
        path: "/music/Senorita - Shawn Mendes_ Camila Cabello.mp3",
        thumb: "https://avatar-ex-swe.nixcdn.com/song/2019/06/21/6/1/8/3/1561114102335_640.jpg",
        iconStatus: '<i class="fas fa-user-friends"></i>',
        duration: "3:11",
    },
    {
        name: "Numb",
        singer: "Linkin Park",
        path: "/music/Numb - Linkin Park.mp3",
        thumb: "https://m.media-amazon.com/images/M/MV5BYmZjOGYzYjYtMTVhZi00NTBmLWI3MjYtMTIwZGJhOTlmNGE4XkEyXkFqcGdeQXVyNzQwMzAwNTI@._V1_.jpg",
        iconStatus: '<span class="badge">ZMA</span>',
        duration: "3:07",
    },
    {
        name: "Bông Hoa Đẹp Nhất",
        singer: "Quân A.P",
        path: "/music/BongHoaDepNhatChillRemix-QuanAP-6817540.mp3",
        thumb: "/images/song-10.jpg",
        iconStatus: "",
        duration: "5:07",
    },
    {
        name: "Viva La Vida",
        singer: "Coldplay",
        path: "/music/Viva La Vida - Coldplay.mp3",
        thumb: "https://images.squarespace-cdn.com/content/v1/5099306be4b0f629c2afcc25/1394041945918-OFEO83X3PTNZ2END8XYI/ke17ZwdGBToddI8pDm48kEU48WT-wucwRp3XFlCQDSt7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1UbvHAMoLgXluVzF2ehXBMnOuOmi5EXYdMsb-Ux5eFX1HB_rxXnGcBlRHfueBT1dxxQ/coldplay.jpg?format=2500w",
        iconStatus: '<span class="badge">ZMA</span>',
        duration: "4:01",
    },
];
