const themes = [
    {
        name: "Chủ đề",
        content: [
            {
                title: "Zing Music Awards",
                thumb: "./images/theme/zma.jpg",
                theme: "./images/theme/bg-zma.svg",
                playerTheme: "./images/theme/bg-player-zma.jpg",
                colors: {
                    bgContentColor: "#ffffff1a",
                    borderBox: "rgb(255 255 255 / 20%)",
                    borderPrimary: "rgb(255 255 255 / 10%)",
                    layoutBg: "#37075d",
                    linkTextHover: "#fe63da",
                    modalScrollbar: "rgba(16,31,63,0.8)",
                    playerBg: "rgba(0,0,0,0.2)",
                    purplePrimary: "#ed2b91",
                    primaryBg: "#6a39af",
                    sidebarPopupBg: "#572f90",
                    textColor: "#fff",
                    textItemHover: "#fff",
                    textSecondary: "rgb(255 255 255 / 50%)",
                    navigationText: "#dadada",
                    placeholderText: "#dadada",
                },
            },
            {
                title: "Tháp Eiffel",
                thumb: "./images/theme/eiffel.jpg",
                theme: "./images/theme/bg-eiffel.jpg",
                colors: {
                    bgContentColor: "#ffffff1a",
                    borderBox: "rgb(255 255 255 / 20%)",
                    borderPrimary: "rgb(255 255 255 / 10%)",
                    layoutBg: "#282828",
                    linkTextHover: "#c662ef",
                    modalScrollbar: "rgba(12,3,3,0.8)",
                    playerBg: "rgba(0,0,0,0.2)",
                    purplePrimary: "#7200a1",
                    primaryBg: "#3d3d3d",
                    sidebarPopupBg: "#292929",
                    textColor: "#fff",
                    textItemHover: "#fff",
                    textSecondary: "rgb(255 255 255 / 50%)",
                    navigationText: "#a0a0a0",
                    placeholderText: "#757575",
                },
            },
        ],
    },
    {
        name: "Nghệ sĩ",
        content: [
            {
                title: "Jack",
                thumb: "./images/theme/artist/jack.jpg",
                theme: "./images/theme/artist/bg-jack.jpg",
            },
            {
                title: "IU",
                thumb: "./images/theme/artist/IU.jpg",
                theme: "./images/theme/artist/bg-IU.jpg",
                colors: {
                    bgContentColor: "rgba(0,0,0,0.05)",
                    borderBox: "rgba(0,0,0,0.2)",
                    borderPrimary: "rgba(0,0,0,0.1)",
                    layoutBg: "#e7dfdd",
                    linkTextHover: "#8c8471",
                    modalScrollbar: "rgba(12,3,3,0.8)",
                    playerBg: "#d0ccc5",
                    purplePrimary: "#409abc",
                    primaryBg: "#fffffe",
                    sidebarPopupBg: "#f2f2f2",
                    textColor: "#32323d",
                    textItemHover: "#409abc",
                    textSecondary: "#696969",
                    navigationText: "#32323d",
                    placeholderText: "#757575",
                },
            },
            {
                title: "Ji Chang Wook",
                thumb: "./images/theme/artist/jichangwook.jpg",
                theme: "./images/theme/artist/bg-jichangwook.jpg",
                colors: {
                    bgContentColor: "#ffffff4d",
                    borderBox: "rgba(0,0,0,0.2)",
                    borderPrimary: "rgba(0,0,0,0.1)",
                    layoutBg: "#b2d8db",
                    linkTextHover: "#239292",
                    modalScrollbar: "rgba(12,3,3,0.8)",
                    playerBg: "#b4d0d0",
                    purplePrimary: "#239292",
                    primaryBg: "#e1e8e8",
                    sidebarPopupBg: "#cce0e0",
                    textColor: "#32323d",
                    textItemHover: "#239292",
                    textSecondary: "#696969",
                    navigationText: "#32323d",
                    placeholderText: "#757575",
                },
            },
            {
                title: "Lisa",
                thumb: "./images/theme/artist/lisa.jpg",
                theme: "./images/theme/artist/bg-lisa.jpg",
                colors: {
                    bgContentColor: "rgba(0,0,0,0.05)",
                    borderBox: "rgba(0,0,0,0.2)",
                    borderPrimary: "rgba(0,0,0,0.1)",
                    layoutBg: "#f9dbdb",
                    linkTextHover: "#ea7aa0",
                    modalScrollbar: "rgba(12,3,3,0.8)",
                    playerBg: "#f9c6c5",
                    purplePrimary: "#ea7aa0",
                    primaryBg: "#fff8f8",
                    sidebarPopupBg: "#fbd3d2",
                    textColor: "#32323d",
                    textItemHover: "#ea7aa0",
                    textSecondary: "#696969",
                    navigationText: "#32323d",
                    placeholderText: "#757575",
                },
            },
            {
                title: "Jennie Kim",
                thumb: "./images/theme/artist/jenniekim.jpg",
                theme: "./images/theme/artist/bg-jenniekim.jpg",
                colors: {
                    bgContentColor: "rgba(0,0,0,0.05)",
                    borderBox: "rgba(0,0,0,0.2)",
                    borderPrimary: "rgba(0,0,0,0.1)",
                    layoutBg: "#bab8c3",
                    linkTextHover: "#8c8471",
                    modalScrollbar: "rgba(12,3,3,0.8)",
                    playerBg: "#c6c4d1",
                    purplePrimary: "#346875",
                    primaryBg: "#e2e7f5",
                    sidebarPopupBg: "#f2f2f2",
                    textColor: "#32323d",
                    textItemHover: "#2a5e6b",
                    textSecondary: "#696969",
                    navigationText: "#32323d",
                    placeholderText: "#757575",
                },
            },
            {
                title: "Jisoo",
                thumb: "./images/theme/artist/jiso.jpg",
                theme: "./images/theme/artist/bg-jiso.jpg",
                colors: {
                    bgContentColor: "rgba(0,0,0,0.05)",
                    borderBox: "rgba(0,0,0,0.2)",
                    borderPrimary: "rgba(0,0,0,0.1)",
                    layoutBg: "#fff",
                    linkTextHover: "#9c32ca",
                    modalScrollbar: "rgba(12,3,3,0.8)",
                    playerBg: "#fff",
                    purplePrimary: "#6b3483",
                    primaryBg: "#fff",
                    sidebarPopupBg: "#f2f2f2",
                    textColor: "#32323d",
                    textItemHover: "#6b3483",
                    textSecondary: "rgba(0,0,0,0.6)",
                    navigationText: "#32323d",
                    placeholderText: "#757575",
                },
            },
            {
                title: "Rosé",
                thumb: "./images/theme/artist/rose.jpg",
                theme: "./images/theme/artist/bg-rose.jpg",
                colors: {
                    bgContentColor: "#ffffff1a",
                    borderBox: "rgb(255 255 255 / 20%)",
                    borderPrimary: "rgb(255 255 255 / 10%)",
                    layoutBg: "#061d50",
                    linkTextHover: "#6e8ffb",
                    modalScrollbar: "rgba(16,31,63,0.8)",
                    playerBg: "rgba(0,0,0,0.2)",
                    purplePrimary: "#3460f5",
                    primaryBg: "#192f60",
                    sidebarPopupBg: "#1d2a49",
                    textColor: "#fff",
                    textItemHover: "#fff",
                    textSecondary: "rgb(255 255 255 / 50%)",
                    navigationText: "#dadada",
                    placeholderText: "#dadada",
                },
            },
        ],
    },
    {
        name: "Màu tối",
        content: [
            {
                title: "Tối",
                thumb: "./images/theme/color/dark.jpg",
            },
            {
                title: "Tím",
                thumb: "./images/theme/color/purple.jpg",
            },
            {
                title: "Xanh đậm",
                thumb: "./images/theme/color/blue.jpg",
            },
            {
                title: "Xanh biển",
                thumb: "./images/theme/color/blue-light.jpg",
            },
            {
                title: "Xanh lá",
                thumb: "./images/theme/color/green.jpg",
            },
            {
                title: "Nâu",
                thumb: "./images/theme/color/brown.jpg",
            },
            {
                title: "Hồng",
                thumb: "./images/theme/color/pink.jpg",
            },
            {
                title: "Đỏ",
                thumb: "./images/theme/color/red.jpg",
            },
        ],
    },
    {
        name: "Màu sáng",
        content: [
            {
                title: "Sáng",
                thumb: "./images/theme/color/light.jpg",
            },
            {
                title: "Xám",
                thumb: "./images/theme/color/gray.jpg",
            },
            {
                title: "Xanh nhạt",
                thumb: "./images/theme/color/green-light.jpg",
            },
            {
                title: "Hồng cánh sen",
                thumb: "./images/theme/color/pink-light.jpg",
            },
        ],
    },
];
