const themes = [
    {
        name: "Chủ đề",
        content: [
            {
                title: "Zing Music Awards",
                slug: "zing-music-awards",
                thumb: "./images/theme/zma.jpg",
                theme: "./images/theme/bg-zma.svg",
                playerTheme: "./images/theme/bg-player-zma.png",
                colors: {
                    primaryBg: "#6a39af",
                    layoutBg: "#37075d",
                    sidebarBg: "hsla(0,0%,100%,0.05)",
                    playerBg: "rgba(0,0,0,0.2)",
                    playerText: "#fff",
                    searchText: "#eee",
                    purplePrimary: "#ed2b91",
                    textItemHover: "#fff",
                    textPrimary: "#fff",
                    textSecondary: "hsla(0,0%,100%,0.5)",
                    linkTextHover: "#fe63da",
                    textPlaceholder: "#dadada",
                    navigationText: "#dadada",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "Tháp Eiffel",
                slug: "eiffel",
                thumb: "./images/theme/eiffel.jpg",
                theme: "./images/theme/bg-eiffel.jpg",
                colors: {
                    primaryBg: "#3d3d3d",
                    layoutBg: "#282828",
                    sidebarBg: "hsla(0,0%,100%,0.05)",
                    playerBg: "rgba(0,0,0,0.2)",
                    playerText: "#fff",
                    searchText: "#eee",
                    purplePrimary: "#7200a1",
                    textItemHover: "#fff",
                    textPrimary: "#fff",
                    textSecondary: "hsla(0,0%,100%,0.5)",
                    linkTextHover: "#c662ef",
                    textPlaceholder: "#757575",
                    navigationText: "#a0a0a0",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
        ],
    },
    {
        name: "Nghệ sĩ",
        content: [
            {
                title: "Jack",
                slug: "jack",
                thumb: "./images/theme/artist/jack.jpg",
                theme: "./images/theme/artist/bg-jack.jpg",
                colors: {
                    primaryBg: "#565147",
                    layoutBg: "#767269",
                    sidebarBg: "hsla(0,0%,100%,0.05)",
                    playerBg: "rgba(0, 0, 0, 0.2)",
                    playerText: "#fff",
                    searchText: "#eee",
                    purplePrimary: "#ac8e77",
                    textItemHover: "#fff",
                    textPrimary: "#fff",
                    textSecondary: "hsla(0,0%,100%,0.5)",
                    linkTextHover: "#d8987f",
                    textPlaceholder: "#dadada",
                    navigationText: "#dadada",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "IU",
                slug: "iu",
                thumb: "./images/theme/artist/IU.jpg",
                theme: "./images/theme/artist/bg-IU.jpg",
                colors: {
                    primaryBg: "#fffffe",
                    layoutBg: "#e7dfdd",
                    sidebarBg: "hsla(0,0%,100%,0.05)",
                    playerBg: "#d0ccc5",
                    playerText: "#32323d",
                    searchText: "#282828",
                    purplePrimary: "#409abc",
                    textItemHover: "#409abc",
                    textPrimary: "#32323d",
                    textSecondary: "#696969",
                    linkTextHover: "#8c8471",
                    textPlaceholder: "#757575",
                    navigationText: "#32323d",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "Ji Chang Wook",
                slug: "ji-chang-wook",
                thumb: "./images/theme/artist/jichangwook.jpg",
                theme: "./images/theme/artist/bg-jichangwook.jpg",
                colors: {
                    primaryBg: "#e1e8e8",
                    layoutBg: "#b2d8db",
                    sidebarBg: "hsla(0,0%,100%,0.3)",
                    playerBg: "#b4d0d0",
                    playerText: "#32323d",
                    searchText: "#282828",
                    purplePrimary: "#239292",
                    textItemHover: "#239292",
                    textPrimary: "#32323d",
                    textSecondary: "#696969",
                    linkTextHover: "#239292",
                    textPlaceholder: "#757575",
                    navigationText: "#32323d",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "Lisa",
                slug: "lisa",
                thumb: "./images/theme/artist/lisa.jpg",
                theme: "./images/theme/artist/bg-lisa.jpg",
                colors: {
                    primaryBg: "#fff8f8",
                    layoutBg: "#f9dbdb",
                    sidebarBg: "hsla(0,0%,100%,0.3)",
                    playerBg: "#f9c6c5",
                    playerText: "#32323d",
                    searchText: "#282828",
                    purplePrimary: "#ea7aa0",
                    textItemHover: "#ea7aa0",
                    textPrimary: "#32323d",
                    textSecondary: "#696969",
                    linkTextHover: "#ea7aa0",
                    textPlaceholder: "#757575",
                    navigationText: "#32323d",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "Jennie Kim",
                slug: "jennie-kim",
                thumb: "./images/theme/artist/jenniekim.jpg",
                theme: "./images/theme/artist/bg-jenniekim.jpg",
                colors: {
                    primaryBg: "#e2e7f5",
                    layoutBg: "#bab8c3",
                    sidebarBg: "rgba(0,0,0,0.05)",
                    playerBg: "#c6c4d1",
                    playerText: "#32323d",
                    searchText: "#282828",
                    purplePrimary: "#346875",
                    textItemHover: "#2a5e6b",
                    textPrimary: "#32323d",
                    textSecondary: "#696969",
                    linkTextHover: "#8c8471",
                    textPlaceholder: "#757575",
                    navigationText: "#32323d",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "Jisoo",
                slug: "jisoo",
                thumb: "./images/theme/artist/jiso.jpg",
                theme: "./images/theme/artist/bg-jiso.jpg",
                colors: {
                    primaryBg: "#fff",
                    layoutBg: "#fff",
                    sidebarBg: "rgba(0,0,0,0.05)",
                    playerBg: "#fff",
                    playerText: "#32323d",
                    searchText: "#282828",
                    purplePrimary: "#6b3483",
                    textItemHover: "#6b3483",
                    textPrimary: "#32323d",
                    textSecondary: "rgba(0,0,0,0.6)",
                    linkTextHover: "#9c32ca",
                    textPlaceholder: "#757575",
                    navigationText: "#32323d",
                    tabActiveBg: "#fff",
                },
            },
            {
                title: "Rosé",
                slug: "rose",
                thumb: "./images/theme/artist/rose.jpg",
                theme: "./images/theme/artist/bg-rose.jpg",
                colors: {
                    primaryBg: "#192f60",
                    layoutBg: "#061d50",
                    sidebarBg: "hsla(0,0%,100%,0.05)",
                    playerBg: "rgba(0,0,0,0.2)",
                    playerText: "#fff",
                    searchText: "#eee",
                    purplePrimary: "#3460f5",
                    textItemHover: "#fff",
                    textPrimary: "#fff",
                    textSecondary: "hsla(0,0%,100%,0.5)",
                    linkTextHover: "#6e8ffb",
                    textPlaceholder: "#dadada",
                    navigationText: "#dadada",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
        ],
    },
    {
        name: "Màu tối",
        content: [
            {
                title: "Tối",
                slug: "toi",
                thumb: "./images/theme/color/dark.jpg",
                colors: {
                    primaryBg: "#282828",
                    layoutBg: "#1e1e1e",
                    sidebarBg: "hsla(0,0%,100%,0.05)",
                    playerBg: "rgba(0,0,0,0.2)",
                    playerText: "#fff",
                    searchText: "#eee",
                    purplePrimary: "#7200a1",
                    textItemHover: "#fff",
                    textPrimary: "#fff",
                    textSecondary: "hsla(0,0%,100%,0.5)",
                    linkTextHover: "#c662ef",
                    textPlaceholder: "#757575",
                    navigationText: "#a0a0a0",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "Tím",
                slug: "tim",
                thumb: "./images/theme/color/purple.jpg",
                colors: {
                    primaryBg: "#432275",
                    layoutBg: "#170f23",
                    sidebarBg: "hsla(0,0%,100%,0.05)",
                    playerBg: "rgba(0,0,0,0.2)",
                    playerText: "#fff",
                    searchText: "#eee",
                    purplePrimary: "#7200a1",
                    textItemHover: "#fff",
                    textPrimary: "#fff",
                    textSecondary: "hsla(0,0%,100%,0.5)",
                    linkTextHover: "#c662ef",
                    textPlaceholder: "#dadada",
                    navigationText: "#dadada",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "Xanh đậm",
                slug: "xanh-dam",
                thumb: "./images/theme/color/blue.jpg",
                colors: {
                    primaryBg: "#192f60",
                    layoutBg: "#101f3f",
                    sidebarBg: "hsla(0,0%,100%,0.05)",
                    playerBg: "rgba(0,0,0,0.2)",
                    playerText: "#fff",
                    searchText: "#eee",
                    purplePrimary: "#3460f5",
                    textItemHover: "#fff",
                    textPrimary: "#fff",
                    textSecondary: "hsla(0,0%,100%,0.5)",
                    linkTextHover: "#6e8ffb",
                    textPlaceholder: "#dadada",
                    navigationText: "#dadada",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "Xanh biển",
                slug: "xanh-bien",
                thumb: "./images/theme/color/blue-light.jpg",
                colors: {
                    primaryBg: "#274a78",
                    layoutBg: "#1d375a",
                    sidebarBg: "hsla(0,0%,100%,0.05)",
                    playerBg: "rgba(0,0,0,0.2)",
                    playerText: "#fff",
                    searchText: "#eee",
                    purplePrimary: "#3460f5",
                    textItemHover: "#fff",
                    textPrimary: "#fff",
                    textSecondary: "hsla(0,0%,100%,0.5)",
                    linkTextHover: "#6e8ffb",
                    textPlaceholder: "#dadada",
                    navigationText: "#dadada",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "Xanh lá",
                slug: "xanh-la",
                thumb: "./images/theme/color/green.jpg",
                colors: {
                    primaryBg: "#126e54",
                    layoutBg: "#124534",
                    sidebarBg: "hsla(0,0%,100%,0.05)",
                    playerBg: "rgba(0,0,0,0.2)",
                    playerText: "#fff",
                    searchText: "#eee",
                    purplePrimary: "#309785",
                    textItemHover: "#fff",
                    textPrimary: "#fff",
                    textSecondary: "hsla(0,0%,100%,0.5)",
                    linkTextHover: "#309785",
                    textPlaceholder: "#dadada",
                    navigationText: "#dadada",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "Nâu",
                slug: "nau",
                thumb: "./images/theme/color/brown.jpg",
                colors: {
                    primaryBg: "#6f514c",
                    layoutBg: "#57403b",
                    sidebarBg: "hsla(0,0%,100%,0.05)",
                    playerBg: "rgba(0,0,0,0.2)",
                    playerText: "#fff",
                    searchText: "#eee",
                    purplePrimary: "#986d5c",
                    textItemHover: "#fff",
                    textPrimary: "#fff",
                    textSecondary: "hsla(0,0%,100%,0.5)",
                    linkTextHover: "#d8987f",
                    textPlaceholder: "#dadada",
                    navigationText: "#dadada",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "Hồng",
                slug: "hong",
                thumb: "./images/theme/color/pink.jpg",
                colors: {
                    primaryBg: "#a22687",
                    layoutBg: "#800064",
                    sidebarBg: "hsla(0,0%,100%,0.05)",
                    playerBg: "rgba(0,0,0,0.2)",
                    playerText: "#fff",
                    searchText: "#eee",
                    purplePrimary: "#d820b0",
                    textItemHover: "#fff",
                    textPrimary: "#fff",
                    textSecondary: "hsla(0,0%,100%,0.5)",
                    linkTextHover: "#fe63da",
                    textPlaceholder: "#dadada",
                    navigationText: "#dadada",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "Đỏ",
                slug: "do",
                thumb: "./images/theme/color/red.jpg",
                colors: {
                    primaryBg: "#883236",
                    layoutBg: "#731717",
                    sidebarBg: "hsla(0,0%,100%,0.05)",
                    playerBg: "rgba(0,0,0,0.2)",
                    playerText: "#fff",
                    searchText: "#eee",
                    purplePrimary: "#aa1c1c",
                    textItemHover: "#fff",
                    textPrimary: "#fff",
                    textSecondary: "hsla(0,0%,100%,0.5)",
                    linkTextHover: "#f36565",
                    textPlaceholder: "#dadada",
                    navigationText: "#dadada",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
        ],
    },
    {
        name: "Màu sáng",
        content: [
            {
                title: "Sáng",
                slug: "sang",
                thumb: "./images/theme/color/light.jpg",
                colors: {
                    primaryBg: "#fff",
                    layoutBg: "#fff",
                    sidebarBg: "rgba(0,0,0,0.05)",
                    playerBg: "#fff",
                    playerText: "#32323d",
                    searchText: "#282828",
                    purplePrimary: "#6b3483",
                    textItemHover: "#6b3483",
                    textPrimary: "#32323d",
                    textSecondary: "rgba(0,0,0,0.6)",
                    linkTextHover: "#9c32ca",
                    textPlaceholder: "#757575",
                    navigationText: "#32323d",
                    tabActiveBg: "#fff",
                },
            },
            {
                title: "Xám",
                slug: "xam",
                thumb: "./images/theme/color/gray.jpg",
                colors: {
                    primaryBg: "#fffffe",
                    layoutBg: "#e5e3df",
                    sidebarBg: "rgba(0,0,0,0.05)",
                    playerBg: "#d0ccc5",
                    playerText: "#32323d",
                    searchText: "#282828",
                    purplePrimary: "#8c8471",
                    textItemHover: "#8c8471",
                    textPrimary: "#32323d",
                    textSecondary: "#696969",
                    linkTextHover: "#8c8471",
                    textPlaceholder: "#757575",
                    navigationText: "#32323d",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "Xanh nhạt",
                slug: "xanh-nhat",
                thumb: "./images/theme/color/green-light.jpg",
                colors: {
                    primaryBg: "#e1e8e8",
                    layoutBg: "#ced9d9",
                    sidebarBg: "hsla(0,0%,100%,0.3)",
                    playerBg: "#b4d0d0",
                    playerText: "#32323d",
                    searchText: "#282828",
                    purplePrimary: "#239292",
                    textPrimary: "#32323d",
                    textSecondary: "#696969",
                    textItemHover: "#239292",
                    linkTextHover: "#239292",
                    textPlaceholder: "#757575",
                    navigationText: "#32323d",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
            {
                title: "Hồng cánh sen",
                slug: "hong-canh-sen",
                thumb: "./images/theme/color/pink-light.jpg",
                colors: {
                    primaryBg: "#fff8f8",
                    layoutBg: "#f9dbdb",
                    sidebarPopupBg: "#fbd3d2",
                    playerBg: "#f9c6c5",
                    playerText: "#32323d",
                    searchText: "#282828",
                    purplePrimary: "#ea7aa0",
                    textPrimary: "#32323d",
                    textSecondary: "#696969",
                    textItemHover: "#ea7aa0",
                    linkTextHover: "#ea7aa0",
                    textPlaceholder: "#757575",
                    navigationText: "#32323d",
                    tabActiveBg: "hsla(0,0%,100%,0.3)",
                },
            },
        ],
    },
];
